version: "3"
services:
  nginx:
      image: nginx:1.23.0
      restart: always
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - /srv/docker/tarot/logs:/var/log/nginx/
      ports:
          - 10131:80
      depends_on:
          - frontend
          - backend

  backend:
    image: tarot/backend:devel
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      API_VERSION: 1.0.0
      API_ENV: "DEV"
      PYTHONPATH: .
    volumes:
      - ./backend/app:/app

  frontend:
    restart: on-failure
    image: tarot/frontend:devel
    stdin_open: true
    build: ./frontend
    container_name: frontend
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/app:/app