version: '3.0'
services:
  backend:
    restart: on-failure
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8001:8000"

  frontend:
    restart: on-failure
    build: ./frontend
    container_name: tarot-app-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true 

  nginx:
    restart: always
    image: nginx:1.23.0
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"